version: '3'
services:
  server:
    container_name: server
    build: .
    command: yarn install
    restart: always
    ports:
      - 3333:3333
    environment:
      - HOST=localhost
      - PORT=3333
      - NODE_ENV=test
      - DEPLOY_URL=https://mycash.com.br
    volumes:
      - .:/usr/app

  db:
    image: ${DOCKER_IMAGE_DB}
    container_name: ${CONTAINER_NAME_DB}
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_DATA}
        # copy the sql script to create tables
      - ${CREATE_TABLES}
        # copy the sql script to fill tables
      - ${FILL_TABLES}
    logging:
      options:
        max-size: 10m
        max-file: '3'
